### ISSUE TITLE
New Code definition in Sonar

### ISSUE THREAD

**Issue by alce65** [isdi-coders-2022/Programadores-Asincronos-202210-mad#52]
Hola de nuevo chic@s
Os falta en Sonar la definición de New Code.
Podéis poner la que queráis, pero poner alguna.
Un par de grupos ya lo tienen, así que podéis preguntarles.

**Comment by AlinaLaurs** [comment]
¡Hola de nuevo Alejandro! Gracias, acabamos de añadir una. Saludos

**Comment by alce65** [comment]
Perfecto,.
Cierro el issue
